name: GP
channels:
  - defaults
dependencies:
  - jupyter=1.0.0
  - matplotlib=3.3.4
  - nose=1.3.7
  - numpy=1.20.1
  - scipy=1.6.2
  - ipywidgets=7.6.3
  - ipympl=0.7.0
  - six=1.15.0
  - pip=21.0.1
  - pip:
    - gpy==1.10.0